package edgareldy.springboottutorial.repository;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

import edgareldy.springboottutorial.config.JpaAuditingConfig;
import edgareldy.springboottutorial.entity.Category;
import jakarta.persistence.EntityManager;
import java.time.temporal.ChronoUnit;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;

/**
 * {@code @DataJpaTest} for {@link CategoryRepository}, backed by a real
 * PostgreSQL instance via Testcontainers rather than an in-memory database,
 * so the schema and constraints exercised match dev/prod exactly.
 * <p>
 * Created edgar.muhamyangabo on 7/4/26
 * Author : edgar.muhamyangabo
 * Date : 7/4/26
 * Project : spring-boot-tutorial
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import({RepositoryTestcontainersConfiguration.class, JpaAuditingConfig.class})
class CategoryRepositoryTest {

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private EntityManager entityManager;

    @Test
    void savesAndFindsCategoryById() {
        Category saved = categoryRepository.save(Category.builder().categoryName("Books").build());

        assertThat(categoryRepository.findById(saved.getId()))
                .isPresent()
                .get()
                .extracting(Category::getCategoryName)
                .isEqualTo("Books");
    }

    @Test
    void savingSetsCreatedAtAndUpdatedAt() {
        Category saved = categoryRepository.save(Category.builder().categoryName("Books").build());

        assertThat(saved.getCreatedAt()).isNotNull();
        assertThat(saved.getUpdatedAt()).isNotNull();
    }

    @Test
    void updatingChangesUpdatedAtButNotCreatedAt() throws InterruptedException {
        Category saved = categoryRepository.saveAndFlush(Category.builder().categoryName("Books").build());
        var originalCreatedAt = saved.getCreatedAt();
        var originalUpdatedAt = saved.getUpdatedAt();
        entityManager.clear();
        Thread.sleep(10);

        Category found = categoryRepository.findById(saved.getId()).orElseThrow();
        found.setCategoryName("Fiction Books");
        Category updated = categoryRepository.saveAndFlush(found);

        // PostgreSQL's timestamp column only keeps microsecond precision, so a
        // value re-read from the database can differ from the in-memory
        // nanosecond-precision Instant Hibernate first generated by a few
        // hundred picoseconds' worth of rounding; compare with tolerance.
        assertThat(updated.getCreatedAt()).isCloseTo(originalCreatedAt, within(1, ChronoUnit.MILLIS));
        assertThat(updated.getUpdatedAt()).isAfter(originalUpdatedAt);
    }

    @Test
    void findAllReturnsSavedCategories() {
        categoryRepository.save(Category.builder().categoryName("Toys").build());
        categoryRepository.save(Category.builder().categoryName("Garden").build());

        assertThat(categoryRepository.findAll()).hasSize(2);
    }
}
