spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_tutorial
    username: spring_boot_tutorial
    password: spring_boot_tutorial
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    edgareldy.springboottutorial: DEBUG
