-- Adds the users table backing feature/auth: JWT-based authentication and
-- per-endpoint authorization (ADMIN vs USER). Role is a simple VARCHAR with
-- a CHECK constraint rather than a separate roles table, since the tutorial
-- only needs two fixed roles and no per-user role combinations.

CREATE TABLE app_users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'USER'))
);
